### ISSUE TITLE
do we need to remove batch effect?

### ISSUE THREAD

**Issue by Roger-GOAT** [zdebruine/RcppML#20]
Hi team, much better than the original NMF on saving time! 
When I did the original NMF, I used
A <- scRNA@assays$integrated@scale.data
all the samples match.
However, in your article, "For example, different normalizations of the data or batch effects can lead to fundamentally different SVD results across most factors. On the other hand, because NMF factors are collectively updated, distinct technical issues are usually explained by a single factor while other factors are left unaffected, making it robust across datasets. "
So I used
A <- scRNA@assays$RNA@counts
But the samples are dispersed. Which one should I use? 
Thanks!

**Comment by zdebruine** [comment]
Thanks for the question, and I'm happy to help.

Let me clarify/guess what exactly it is you are doing:
* You have two different experiments, with a batch effect between them
* You integrate using Seurat (possibly rPCA?) which involves scaling counts, then run NMF on scaled count data, and notice that UMAP on NMF coordinates looks nice (no obvious batch effect)
* You go back and run NMF on raw counts, but find the UMAP on NMF coordinates does not look nice (obvious batch effect persists)

There's a reason for this:  there is a factor (or several factors) in your NMF model that captures the batch effect, and so that factor(s) is moving the UMAP coordinates of affected cells by a corresponding amount.  If the experiments describe similar information, you can look for factors in your model that are higher in samples from one experiment vs. the other experiment.  It is at your discretion to remove these factors from the model, because they are explaining batch effects and not biological signal. 
 Once you remove those "bad" factors, run UMAP again and samples should be aligned.

I'm planning to write a vignette on integrating latent models from multiple single-cell experiments in the future.  I'll leave this issue open until I get to that.

If I'm not sufficiently clear, please ask further!
